import 'dart:convert';
import 'dart:io';

/// Build-time secret obfuscation for LastWave Desktop.
///
/// Mirrors LastWave-native's `obfuscateSecret()` (XOR each byte with a
/// repeating mask, stored as byte arrays in BuildConfig, decoded at
/// runtime via `decodeSecretBytes`):
///
///   dart tool/obfuscate_secrets.dart
///
/// Reads `.env` from the project root, XOR-obfuscates the secret
/// values with the same mask, and generates
/// `lib/core/env/secrets.g.dart` (gitignored — never committed).
/// Run again after changing `.env` and before release builds.
///
/// This deters casual string-dumping of the binary — the same threat
/// model as the Android app — and means no plaintext `.env` asset
/// ships inside the built application.
const _mask = [0x5A, 0x3F, 0x7E, 0x1B, 0x92, 0x4C, 0xA1, 0x6D];

const _keys = [
  'ADDON_CLIENT_SECRET',

  'LYRICS_API_KEY',
];

String _constName(String key) {
  final parts = key.toLowerCase().split('_');
  final camel = parts.first +
      parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
  return 'k${camel[0].toUpperCase()}${camel.substring(1)}';
}

void main() {
  final root = Directory.current.path;
  final envFile = File('$root${Platform.pathSeparator}.env');
  final values = <String, String>{};
  if (envFile.existsSync()) {
    for (final line in envFile.readAsLinesSync()) {
      final m = RegExp(r'^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$')
          .firstMatch(line);
      if (m != null) {
        var v = m.group(2)!.trim();
        if ((v.startsWith('"') && v.endsWith('"') && v.length >= 2) ||
            (v.startsWith("'") && v.endsWith("'") && v.length >= 2)) {
          v = v.substring(1, v.length - 1);
        }
        values[m.group(1)!] = v;
      }
    }
  }

  final buf = StringBuffer()
    ..writeln('// GENERATED by `dart tool/obfuscate_secrets.dart`.')
    ..writeln('// Do not edit by hand. Do not commit (see .gitignore).')
    ..writeln();
  for (final key in _keys) {
    final bytes = utf8.encode(values[key] ?? '');
    final obfuscated = List<int>.generate(
      bytes.length,
      (i) => bytes[i] ^ _mask[i % _mask.length],
    );
    buf.writeln('/// Obfuscated bytes for `$key`.');
    buf.writeln(
        'const List<int> ${_constName(key)} = <int>[${obfuscated.join(', ')}];');
    buf.writeln();
  }
  final outPath =
      '$root${Platform.pathSeparator}lib${Platform.pathSeparator}core${Platform.pathSeparator}env${Platform.pathSeparator}secrets.g.dart';
  File(outPath).writeAsStringSync(buf.toString());

  var filled = 0;
  for (final key in _keys) {
    if ((values[key] ?? '').isNotEmpty) filled++;
  }
  // ignore: avoid_print
  print('secrets.g.dart written ($filled/${_keys.length} keys set).');
}
